### ISSUE TITLE
Error message: remove(x): x not in list

### ISSUE THREAD

**Issue by Felina-Lain** [Jandals/HairNet#14]
Hello
First thanks for this amazing addon, it's saving me so much time in my work!

Sadly I've been getting this error while I work:

`Traceback (most recent call last):
  File "C:\Users\Felina\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\HairNet\__init__.py", line 963, in draw
    self.drawDetails(self.layout, context)
  File "C:\Users\Felina\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\HairNet\__init__.py", line 985, in drawDetails
    self.hairObjList.remove(self.headObj)
ValueError: list.remove(x): x not in list

location: <unknown location>:-1`

It doesn't seem to be doing anything, it just flash in the console, but since not seeing a problem doesn't mean there won't be one later, I figured I'd signal it

**Comment by Jandals** [comment]
Thanks for sending this in. It looks like it's an error in drawing the properties panels. It might lead to trouble as the script's settings get changed, but it sounds like it's not critical.

I'll see if I can clean it up.
