### ISSUE TITLE
HairNet not working in Blender 2.9

### ISSUE THREAD

**Issue by sirdavid32** [Jandals/HairNet#17]
![error](https://user-images.githubusercontent.com/11066585/91860407-3e3d9f80-ec31-11ea-931a-53ec947dca94.png)
I ran Hair Net in Blender 2.9, I don't know what else do I need to set up for it to work.
Currently, this is the error that presents. 
Please let us know if it will be working for Blender 2.9
Thanks!

**Comment by Felina-Lain** [comment]
I corrected that error in my script, by copying the line in the first "if" of that function
![image](https://user-images.githubusercontent.com/5339303/92393824-c71c7580-f120-11ea-991b-dda5e9d82f9d.png)

But now I'm getting another error, and this one I'm not sure how to bypass:
![image](https://user-images.githubusercontent.com/5339303/92393891-e0bdbd00-f120-11ea-9937-3a52d01b650f.png)

**Comment by Jandals** [comment]
HairNet has been updated and version 0.6.2 seems to be working in 2.9. It's available in the "releases" page.
sirDavid, if you still have the problem in the new version, please provide some more information about what causes the error.

**Comment by Felina-Lain** [comment]
> HairNet has been updated and version 0.6.2 seems to be working in 2.9. It's available in the "releases" page.
> sirDavid, if you still have the problem in the new version, please provide some more information about what causes the error.

I updated to 0.6.2
and Now I get this error:

```
Traceback (most recent call last):
  File "E:\LiberKey\Apps\Blender\App\Blender\x86\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Felina\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\HairNet\__init__.py", line 28, in <module>
    from import_properties import *
ModuleNotFoundError: No module named 'import_properties'
```

**Comment by Jandals** [comment]
Thanks for tracking that down. The syntax change has been giving me some trouble. The import was originally written as you put it but I couldn't get THAT to work. I expect that's a problem with my local machine so I'll try to sort it out and get the release updated.

**Comment by Jandals** [comment]
It seems to be working again. There were namespace problems between the development environment and the installed environment. I worked around it and it seems to be alright.

**Comment by nanatsu1993** [comment]
Hello everyone,

I just downloaded the version 0.6.2 of hairnet to use it on blender 2.9, unfortunately I'm still having problems.

below screenshot of the errors.

Thank you in advance for your answer.

![Sans titre](https://user-images.githubusercontent.com/71676161/93832192-da752800-fc6c-11ea-9470-b73e303c8e38.jpg)

**Comment by Jandals** [comment]
Nanatsu,

From the image you shared, it seems like what HairNet is trying to do is create a hair system on a curve object. Which isn't allowed in Blender.

HairNet should catch that and prevent a user from running into this error. That'll need to be fixed.

HairNet needs the last-selected object to be a mesh object, not a curve, so it can create a hair system on it.

If something else is going on, please include some more details about what is happening.
