### ISSUE TITLE
0.6.3 not even installing. Traceback below:

### ISSUE THREAD

**Issue by JDBlenderer** [Jandals/HairNet#23]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Tzaddi Tabigne\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\hairNet\__init__.py", line 37, in <module>
    from . import hairNet
  File "C:\Users\Tzaddi Tabigne\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\hairNet\hairNet.py", line 33, in <module>
    import pydevd
ModuleNotFoundError: No module named 'pydevd'

**Comment by comicsserg** [comment]
I just tested and have the same issue as you
![image](https://user-images.githubusercontent.com/63783506/103203417-292e0000-48f5-11eb-96cd-22e91217f15b.png)

**Comment by Jandals** [comment]
Sorry. I left a flag enabled. I have updated v0.6.3, which should load. correctly.
https://github.com/Jandals/HairNet/releases/tag/v0.6.3

**Comment by JDBlenderer** [comment]
It's fixed now
Thanks

**Comment by comicsserg** [comment]
I am not able to use the addon for some reason, when selecting curve and then shift selecting the mesh with hair system on it and clicking on the button from curve I get an error

Python: Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\hairNet\hairNet.py", line 612, in invoke
    
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\hairNet\hairNet.py", line 583, in execute
    self.report(type = {'ERROR'}, message = "Mesh guides have different lengths")
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\hairNet\hairNet.py", line 685, in createHair
    if options[3]:
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties:  PARTICLE_OT_brush_edit.stroke error converting a member of a collection from a dicts into an RNA collection, failed with: TypeError: Converting a Python list to an RNA collection: keyword "mouse_event" missing


location: <unknown location>:-1

The origin of the curver is at 0,0,0
