### ISSUE TITLE
Hair from sheet: python error

### ISSUE THREAD

**Issue by Felina-Lain** [Jandals/HairNet#53]
Hello, as title says, I'm getting an error and the addon doesn't work.
I'm on blender 3.3, hairnet 0.6.7, here's what I did:

Create a scalp mesh. Create a guide mesh, made of multiple planes, all with the same amount of vertex (I ctrl+d the first plane to make sure of that). Selected the top edge and marked as seam.
![image](https://user-images.githubusercontent.com/5339303/197397257-0dad2b60-cb08-41ec-8969-f08b022a7ba1.png)
Selected guide, then scalp in object mode. Pressed the "from sheet" button

This is what I get:
`Python: Traceback (most recent call last):
  File "******\hairNet\hairNet.py", line 697, in invoke
    return self.execute(context)
  File "******\hairNet\hairNet.py", line 668, in execute
    self.createHair(targetObject, hairGuides, options)
  File "******\hairNet\hairNet.py", line 771, in createHair
    bpy.ops.particle.brush_edit(stroke=[{'name':'','location':(0, 0, 0), 'mouse':(0, 0), 'mouse_event':(0, 0), 'pressure':0, 'size':0, 'pen_flip':False, "x_tilt":0, "y_tilt":0, 'time':0, 'is_start':False}])
  File "*******\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.particle.brush_edit.poll() failed, context is incorrect
`

Can anyone help me find what I did wrong?

**Comment by Jandals** [comment]
It looks like this an issue I thought had been resolved.

Could you share this file with me so I can track down where it's going wrong?

**Comment by Felina-Lain** [comment]
Sure, here it is: https://we.tl/t-75G5jGhYZc
I edited the guide mesh but it's still getting the same error, and it's still made from one object that I ctrl+d several times

**Comment by MoogieOuttaMyDepth** [comment]
Error still exists, any fix on the horizon? I tried manually fixing this myself using the information [from here](https://blender.stackexchange.com/questions/6101/poll-failed-context-incorrect-example-bpy-ops-view3d-background-image-add) but it still gave incorrect context. I tried both the legacy and Temp Override ways, neither worked. I suspect I just didn't give it the correct context, but Google won't tell me what context the particle brush requires.

Edit: Well I think I found the correct context ('PARTICLE_EDIT') but the problem is I can't have the particle edit view open without giving the scalp a particle system first, and if I do that, and switch to that view, then the HairNet panel disappears and takes the button I need to click with it!
