### ISSUE TITLE
Keep getting this error when turning curves into particle system

### ISSUE THREAD

**Issue by bruhlol1a** [Jandals/HairNet#55]
If you could help me out, please and thank you. 

btw I am using 3.3.0 blender and the latest Hairnet, the curve were converted from a mesh. 

Python: Traceback (most recent call last):
  File "C:\Users\shado\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\hairNet\hairNet.py", line 697, in invoke
    return self.execute(context)
  File "C:\Users\shado\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\hairNet\hairNet.py", line 590, in execute
    options[2] = makeNewHairSystem(targetObject,sysName)
  File "C:\Users\shado\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\hairNet\hairNet.py", line 335, in makeNewHairSystem
    headObject.particle_systems[-1].name = systemName
IndexError: bpy_prop_collection[-1]: out of range.

location: <unknown location>:-1

**Comment by Jandals** [comment]
I only get this error when I have the curve as the last-selected object. HairNet needs you to select the curves first and then select the object where you want hair to grow last.

Does that change anything for you?

**Comment by joerno** [comment]
I have the same error with Blender 3.1.2 und 3.4.1, no matter what the last selected object is

**Comment by ghost** [comment]
I got the same error when I try to add hair from curve, but only with curves converted from mesh(I believe this is what's called a poly curve). Also, I selected the curve first and the target object last. Version is blender 2.9.0 and hairnet 0.6.2.

Tried this again in blender 3.0.1 and hairnet 0.6.7. and this worked OK except blender randomly crashes..
